# Remote pe.audio.sys host (or IP)
remote = my_dsp_host.local

# JackTrip Queue Buffer Length, in Packet Size (default 4)
queue = 4

# JackTrip Packet Redundancy to avoid glitches with packet losses (default 1)
redundancy = 1
