#!/bin/bash

# DVB-T
#$HOME/pe.audio.sys/share/scripts/DVB-T.py preset 1
#sleep .5 # because retuning takes a bit
#echo "input tdt" | nc -N localhost 9989

# Internet
$HOME/pe.audio.sys/share/scripts/istreams.py preset 1
sleep .5 # because retuning takes a bite
echo "input istreams" | nc -N localhost 9989

# RNE radio program uses to have a very high loudness
# config.yml.on_change_input or source settings will restore if desired
echo "loudness_ref 9" | nc -N localhost 9989
