#!/bin/bash

$HOME/pe.audio.sys/share/scripts/DVB-T.py preset 1

sleep .5 # because retuning takes a bit
echo "input tdt" | nc -N localhost 9989

# RNE broadcast comes super compressed, so 
# it is better to deactivate loudness compensation
echo "loudness off" | nc -N localhost 9989
# config.yml.on_change_input will restore loudness if desired
