#!/bin/bash

#
# A command line tool to control the system
#

# Reading addresses and ports from the config file
SRV_ADDR=$( grep pasysctrl_address ~/pe.audio.sys/config.yml | awk '{print $NF}' )
SRV_ADDR=${SRV_ADDR//\"/}; SRV_ADDR=${SRV_ADDR//\'/}
SRV_PORT=$( grep pasysctrl_port ~/pe.audio.sys/config.yml | awk '{print $NF}' )

if [[ $(uname) == *'Linux'* ]];then
    # 'nc' on Linux: -N shutdown the network socket after EOF on the input.
    echo "$@" | nc -N $SRV_ADDR $SRV_PORT
else
    # 'nc' on Mac OS:
    echo "$@" | nc    $SRV_ADDR $SRV_PORT
fi

echo ''
