#!/usr/bin/env python3

print('Importing examples/radio_macro.py ...')
import examples.radio_macro as rm


rm.mplayer_profile = 'istreams'   # choose an Mplayer profile: "istreams", "dvb"
rm.preset          = 1            # your DVB or istreams preset number here
rm.lu_offset       = 9
rm.loudness_comp   = 'off'
rm.xo_pattern      = 'mp'
rm.drc_pattern     = 'mp'

rm.main()
