#!/bin/bash

###############################################
# configure here mode="internet" or "dvbt"
mode="internet"
###############################################

if [[ $mode == "dvbt" ]]; then
    $HOME/pe.audio.sys/share/scripts/DVB-T.py preset 3
    sleep .5 # because retuning takes a bit
    echo "input tdt" | nc -N localhost 9990

elif [[ $mode == "internet" ]]; then
    $HOME/pe.audio.sys/share/scripts/istreams.py preset 3
    sleep .5 # because retuning takes a bite
    echo "input istreams" | nc -N localhost 9990

else
    exit 0
fi

# Radio 3 music program uses to have a high loudness LU level (pop & rock mastering)
# config.yml.on_change_input or source settings will restore if desired
echo "loudness_ref 6" | nc -N localhost 9990
