#!/bin/bash

# Stop the current player
control player pause

# Select source
control input "mpd"

# Adjust the expected loudness reference level
control loudness_ref 3

# Adjust MPD settings
mpc replaygain off

# Load and shuffle your favourite playlist
mpc clear
mpc load NAS_Jazz
mpc shuffle
mpc play
