#!/bin/bash

# Stop the current player
peaudiosys_control player pause

# Select source
peaudiosys_control input "mpd"

# Adjust the expected loudness reference level
peaudiosys_control loudness_ref 3

# Adjust MPD settings
mpc replaygain off

# Load and shuffle your favourite playlist
mpc clear
mpc load "Jazz"
mpc shuffle
mpc play
