#!/usr/bin/env python3
"""
    Toggles preamp to listen to BT_devices configured inside config.sys

    This needs Pulseaudio (see doc/80_Pulseaudio.md), alongside
    the 'scripts/pulseaudio-BT.py' to be called from config.yml

"""
import sys
import os
UHOME = os.path.expanduser("~")
sys.path.append(f'{UHOME}/pe.audio.sys')
from share.miscel import send_cmd


if __name__ == "__main__":

    # Print help
    if sys.argv[1:] and '-h' in sys.argv[1]:
        print(__doc__)
        sys.exit()

    send_cmd('preamp input BT')

