#!/usr/bin/env python3
"""
    Load an alternate loudspeaker, by using the template 'lspk_macro.py'
"""

import  templates.lspk_macro as lm


# First of all, before calling main(), you need to define MY_LSPK

lm.MY_LSPK = {  'name':     'DynC5',
                'drc_set':  'equilat',
                'xo_set':   ''
             }


lm.main()
