#!/usr/bin/env python3
"""
    Alternates between two loudspeaker sets, both attached to differents
    channels ports from the same system sound card.

    You need to prepare a macro file whose filename must contain the
    belonging loudspeaker name.


    ACHTUNG this is purely geek  >:-)

"""

import  os
import  sys
from    subprocess import Popen

UHOME       = os.path.expanduser("~")
MAINFOLDER  = f'{UHOME}/pe.audio.sys'

sys.path.append( f'{MAINFOLDER}/share/miscel' )
from miscel import CONFIG, get_macros


#########   SETS OF LOUDSPEAKERS TO TOGGLE BETWEEN      ########
LSPK_A = "DynC5"
LSPK_B = "cardiojorns"
################################################################


if __name__ == "__main__":

    verbose = False
    if '-v' in sys.argv[1:]:
        verbose = True


    # Toggling
    curr_lspk = CONFIG["loudspeaker"]
    if curr_lspk == LSPK_A:
        new_lspk = LSPK_B
    else:
        new_lspk = LSPK_A


    # Retrieving the macro for the "new_lspk"
    mNames = get_macros()
    mName = ''
    for m in mNames:
        if m.endswith(new_lspk):
            mName = m


    # Running the macro
    if mName:
        print( f'Switching to {new_lspk} ({mName})' )
        if verbose:
            Popen( f'{MAINFOLDER}/macros/{mName}'.split() )
        else:
            with open('/dev/null', 'w') as fnull:
                Popen( f'{MAINFOLDER}/macros/{mName}'.split(),
                        stdout=fnull, stderr=fnull)

